
version: '3.7'

services:

  nginx:
    container_name: cyber-dojo-nginx

  custom-start-points:
    container_name: cyber-dojo-custom-start-points
  exercises-start-points:
    container_name: cyber-dojo-exercises-start-points
  languages-start-points:
    container_name: cyber-dojo-languages-start-points

  custom-chooser:
    container_name: cyber-dojo-custom-chooser
  exercises-chooser:
    container_name: cyber-dojo-exercises-chooser
  languages-chooser:
    container_name: cyber-dojo-languages-chooser

  creator:
    container_name: cyber-dojo-creator

  avatars:
    container_name: cyber-dojo-avatars

  web:
    container_name: cyber-dojo-web

  runner:
    container_name: cyber-dojo-runner

  differ:
    container_name: cyber-dojo-differ

  saver:
    container_name: cyber-dojo-saver

  zipper:
    container_name: cyber-dojo-zipper
